apiVersion: v1
kind: Secret
metadata:
  name: {{ include "static-site.fullname" . }}-secret
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
    environment: {{ .Values.environment }}
type: Opaque
stringData:
  SECRET: {{ .Values.secrets.SECRET | quote }}
